### ISSUE TITLE
Github integration broken

### ISSUE THREAD

**Issue by nijel** [bountysource/core#1062] opened 2016-11-04 09:29 UTC
Some recent changes on GitHub (probably I didn't check) has broken adding text to GitHub issues - the xml markup is now shown as is including it's content.

For example see following issues:

* https://github.com/duplicati/duplicati/issues/2026
* https://github.com/nijel/weblate/issues/1267

Removing the

 tags the text render properly again.

**Comment by nijel** [comment] 2016-11-04 09:29
Screenshot showing current state (in case the issues got modified/fixed):

![support_parallel_uploads_for_a_backend_ 50 _ _issue_ 2026_ _duplicati_duplicati_-_2016-11-04_10 29 23](https://cloud.githubusercontent.com/assets/212189/20000790/9511e5a6-a279-11e6-9cbe-740272db19f5.png)

**Comment by Mailaender** [comment] 2016-11-05 06:38
Confirmed, it is completely broken now https://github.com/OpenRA/OpenRA/issues/2743

![image](https://cloud.githubusercontent.com/assets/756669/20028168/8958b472-a32a-11e6-9576-965bbc187781.png)

Not just not updating the $ amounts anymore. https://github.com/bountysource/core/issues/1011

**Comment by denschub** [comment] 2016-11-06 05:20
This is annoying for us (diaspora) as well. @wkonkel, is this stuff even maintained anymore?

**Comment by Mailaender** [comment] 2016-11-06 06:53
I don't think anyone at BountySource cares. But how do we get rid of this terrible integration feature? Lot's of older tickets at https://github.com/OpenRA/OpenRA/issues are effected and manually cleaning them up would be tedious.

**Comment by sualko** [comment] 2016-11-07 08:09
@wkonkel @rappo This is really urgent. If this feature is no longer maintained, please remove it.

> But how do we get rid of this terrible integration feature?

Probably someone has to write a little script to remove that crap. Any volunteers? :laughing:

**Comment by tuxedo0801** [comment] 2016-11-09 19:22
bountysource.com seems to be down... ?!

**Comment by Mailaender** [comment] 2016-11-10 21:41
I just manually cleaned up @OpenRA and will think twice before activating such a feature again.

**Comment by lukespragg** [comment] 2016-11-11 16:49
Also noticing this. It seems that the <bountysource-plugin> tags are not hidden by GitHub now, and the formatting is a bit off which causes it to show as a jumbled mess. I know Bountysource relies on the tags for the plugin to detect the text in the body and update it if needed, so removing those tags likely wouldn't work well.

https://github.com/bountysource/core/blob/125ca8d0d427e369e33b77fdab198b53a26616ee/app/models/tracker_plugin/gh.rb#L135-L137

https://github.com/bountysource/core/blob/125ca8d0d427e369e33b77fdab198b53a26616ee/app/models/tracker_plugin/gh.rb#L238-L253

**Comment by indazoo** [comment] 2016-11-12 06:08
I'm new to bountysource and wanted to use it to find a solution on a Github project. Two days ago (or so) bountysource.com was down for two days. It seems to be up again.
Today, kintel pointed me to this issue.
As reported above, it seems not to work for Github, even though on the now working website is a large box to post bounties for GitHub issues. Does the here reported issue with the XML Markup influence the possibility of a developer who fixed my issue on the other project to earn the money via bountysource? Are there any special steps to take until this is fixed?

**Comment by sualko** [comment] 2016-11-14 08:27
@indazoo from my point of view, this issue is not related to the other bountysource services.

**Comment by aspiers** [comment] 2016-11-19 11:25
@sualko Please can you explain why not, for those of us new to bountysource?

**Comment by aspiers** [comment] 2016-11-19 11:57
I think I have found a potential fix: adding a blank line immediately after the first `<bountysource-plugin>` causes it to render correctly:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38857851-break-on-pattern-match-functionality?utm_campaign=plugin&utm_content=tracker%2F449456&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F449456&utm_medium=issues&utm_source=github).
</bountysource-plugin>

vs.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38857851-break-on-pattern-match-functionality?utm_campaign=plugin&utm_content=tracker%2F449456&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F449456&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by tuxedo0801** [comment] 2016-11-19 12:07
Yes, that fixes the issue "manually". Question is: Why is not an addition linebreak needed?!

**Comment by kenorb** [comment] 2016-11-20 15:13
Same here: https://github.com/FX31337/FX-BT-Scripts/issues/66

It shows the plain code, e.g.:
`--- Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35030302-script-to-read-mqlcache-dat?utm_campaign=plugin&utm_content=tracker%2F20487492&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F20487492&utm_medium=issues&utm_source=github).`

**Comment by simonmichael** [comment] 2016-12-11 18:38
Hey BountySource, can you respond here or blog or something to give us a rough ETA for when this will be fixed ? The manual linebreak workaround has to be re-applied every time the status changes. It's really annoying.

**Comment by antenore** [comment] 2016-12-12 21:48
Just to add some more voice, at [@FreeRDP/Remmina](https://github.com/FreeRDP/Remmina) we have the same issue.  I'd help knowing how, but here the @bountysource team have the whole responsibility.

**Comment by tuxedo0801** [comment] 2016-12-13 08:00
Has anyone found out how to get (comletely) rid of bounty source? This issue is really annoying and noone @bountysource cares ...

**Comment by nijel** [comment] 2016-12-13 08:16
You can at least disable GitHub issues body editing (under [Tools](https://www.bountysource.com/tools/installed) just uncheck "Modify issue bodies" for each issue tracker you maintain). It does remove existing markup from the issue bodies. There is just minor cruft that stays (extra ``##``), but it's not really problematic and not that visible.

**Comment by tuxedo0801** [comment] 2016-12-13 08:29
Under Tools I now disabled all the checkboxes for all repos, I unlinked my GH account on bountysource.com and revoked the authorization in my GH organization settings. 

So I'm no longer bound to bountysource. Issue solved for me.

**Comment by kenorb** [comment] 2016-12-13 21:31
### Workaround

Go to: https://www.bountysource.com/tools/installed page, then select the affected repository and unselect _Modify issue bodies_ option.

<img width="282" alt="screen shot 2016-12-13 at 21 30 24" src="https://cloud.githubusercontent.com/assets/266306/21160066/716d8bde-c17b-11e6-822d-b800f098e6a4.png">

**Comment by kaikreuzer** [comment] 2016-12-14 07:35
> So I'm no longer bound to bountysource. Issue solved for me.

I guess as long as there are no statements or comments from @wkonkel or @rappo, this is really the only solution as we have to consider Bountysource to be abandoned and dead - which is really a pity as it is a great idea and imho there is nothing similar out there. Or does anyone know about alternatives?

**Comment by kenorb** [comment] 2016-12-14 11:00
Btw. There is a similar project called [Codemill](http://codemill.io/).

**Comment by tuxedo0801** [comment] 2016-12-14 11:07
@kenorb 
Thanks for the link to an alternative. But, well, it's only similar. It works (for me) the other way around:
 BountySource enables others to pay for implementation/bugfixing (so I can earn money when solving an issue (even on my project) someone else has set a bounty on). Codemill enables me (as project owner) to pay for implementation/bugfixing done by others. 
Other alternatives are welcome ;-)

**Comment by wkonkel** [comment] 2016-12-14 16:16
Hello everyone, sorry for not responding sooner. Bountysource has not been abandoned. That said, @rappo and I have extremely limited time at the moment that we can dedicate to Bountysource and we've been focusing on the highest priority items like processing cash outs and fixing the database instability that's been causing downtime over the past month or two. We hope to have more time for Bountysource after the holidays. Also, since Bountysource is OSS, soon we're going to be asking our communuty if there are any developers who want to join as "core contributors", so if you know Ruby on Rails or Angular.js, please consider volunteering!

Regarding this ticket in particular, it seems as if GitHub changed their markdown engine to show unrecognized HTML tags. We were using those tags to keep track of the text we were adding. Since those tags are no longer supported, the code needs to be updated to do two things: remove those tags from existing issues; and keep issues updated in a way that doesn't require those tags anymore.

Unfortunately, I won't have time to work on this until after the holidays, but if somebody else is able to work on this, I'll happily review the PR and merge.

**Comment by simonmichael** [comment] 2016-12-14 16:19
Thanks for the update @wkonkel, that helps.

**Comment by aspiers** [comment] 2016-12-15 13:03
@wkonkel I think the fix is much simpler than you seem to be suggesting here - there's no need to strip unrecognised tags.  If you didn't already see [my previous comment](https://github.com/bountysource/core/issues/1062#issuecomment-261709829), please read it - thanks!

**Comment by antenore** [comment] 2016-12-15 14:09
@aspiers maybe you can propose a pull request? Personally I've some ideas but I'm not sure where and how to apply it.. Can you try? We can than review it... We are some tens of users, we should be able to find it out no? Please! Let's try!

**Comment by antenore** [comment] 2016-12-15 14:11
https://github.com/bountysource/core/blob/125ca8d0d427e369e33b77fdab198b53a26616ee/app/models/issue.rb#L424 This should be the right place.

**Comment by kenorb** [comment] 2016-12-15 15:38
@wkonkel If GitHub shows unrecognized HTML tags, this can be hidden by commenting out these tags and use the extension to read it.

E.g. `<!-- <plugin-tag> </plugin-tag> -->`.

**Comment by aspiers** [comment] 2016-12-16 02:02
@kenorb wrote:
> @wkonkel If GitHub shows unrecognized HTML tags

It doesn't, and this is not the problem.

> this can be hidden by commenting out these tags and use the extension to read it.

The fix is even simpler, as mentioned in my [previous](https://github.com/bountysource/core/issues/1062#issuecomment-267322337) two [comments](https://github.com/bountysource/core/issues/1062#issuecomment-261709829).

**Comment by aspiers** [comment] 2016-12-16 02:05
@antenore It doesn't look like the right place to me - that's removing the footer not adding it.  The same is true for the other result in [this search for `bountysource-plugin`](https://github.com/bountysource/core/search?utf8=%E2%9C%93&q=bountysource-plugin).  I haven't yet found where it gets added.

**Comment by aspiers** [comment] 2016-12-16 09:26
@wkonkel @rappo As per previous comment and [this search for `bountysource-plugin` across the whole of GitHub](https://github.com/search?q=bountysource-plugin&type=Code&utf8=%E2%9C%93), it seems that the code which inserts the footer simply doesn't exist on GitHub.  That's a shame, because if it did, I'm pretty sure I could have submitted a PR to fix this pretty quickly.  Even if you don't have time to work on it yourselves, presumably it would only take you a minute to give us a pointer as to where this code lives so we can fix it?

**Comment by nijel** [comment] 2016-12-16 09:34
It's there (I have no clue why search doesn't show it now, it did find it some time ago when I've searched):

https://github.com/bountysource/core/blob/125ca8d0d427e369e33b77fdab198b53a26616ee/app/models/tracker_plugin/gh.rb#L253

**Comment by antenore** [comment] 2016-12-16 10:27
I've proposed the #1068 ... It may be wrong, so please review and (obviously) feel free to change/improve/discard /merge it.

@wkonkel What do you think?

**Comment by carlin-q-scott** [comment] 2017-01-17 14:36
antenore fixed the problem with his PR I'm pretty sure but someone also needs to do something about the existing GitHub issues. Maybe a one-off script which each repo maintainer can run?

**Comment by wetneb** [comment] 2017-01-28 23:57
yes please! https://github.com/OpenRefine/OpenRefine/issues/805 is out of sync.

**Comment by rlogiacco** [comment] 2017-02-02 15:36
A recently opened issue on Github is displayed incorrectly: https://github.com/rlogiacco/Natural/issues/49

This is a long thread: is there anything I can do other than remove the bountysource integration?

**Comment by untitaker** [comment] 2017-02-02 15:37
No.

**Comment by Kostronor** [comment] 2017-02-03 13:11
Since this hit us too, I'm opening a small bounty 😉 
https://www.bountysource.com/issues/38949610-github-integration-broken

**Comment by rappo** [comment] 2017-02-13 06:11
wkonkel merged and deployed @antenore's PR (https://github.com/bountysource/core/pull/1068) tonight. Hopefully this fixes everyone's issue. Thanks for the PR

**Closed by rappo** 2017-02-13 06:11 UTC

**Comment by Kostronor** [comment] 2017-02-13 09:07
Nice! @antenore can claim the bounty once it is deployed and working :)

**Comment by antenore** [comment] 2017-02-13 09:19
My fix is so insignificant that I'll reuse it for something else, hopefully related to bountysource :-)

**Comment by Kostronor** [comment] 2017-02-13 09:22
@antenore sounds good! I tested it and it is working perfectly. So just claim it :)

**Comment by jcbrand** [comment] 2017-02-13 09:23
@antenore Perhaps a small fix, but definitely not insignificant!

**Comment by DarthGandalf** [comment] 2017-02-25 12:22
@rappo I still have many broken issues, e.g. https://github.com/znc/znc/issues/1354, can you batch-fix all existing ones?

**Comment by DarthGandalf** [comment] 2017-03-14 23:34
@rappo ping?

**Comment by snipe** [comment] 2017-03-14 23:35
I'd also love this fix for snipe/snipe-it. Bounty prompting footer and labels haven't worked in ages.

**Comment by antenore** [comment] 2017-03-14 23:43
As the code has been fixed, probably the best and faster solution for everybody is to disable en re-enable the bounty integration into GitHub.

Let me know if it works (it should)

**Comment by snipe** [comment] 2017-03-14 23:44
> As the code has been fixed, probably the best and faster solution for everybody is to disable en re-enable the bounty integration into GitHub.

That was the first thing I tried. No luck.

**Comment by antenore** [comment] 2017-03-14 23:49
Weird. Have to say that between the  two I've personally waited more than 2/3 weeks. 
I don't know how it works bounty behind the scenes, but it could be they have a caching system, so maybe you have re-enabled bounty too fast (?), or a kind of build process ???  Dunno... But try again and maybe waiting some few days.
Sorry for the conjectures, I really don't know how it works

**Comment by carlin-q-scott** [comment] 2017-03-29 20:21
Did @antenore 's idea work for anyone? I doubt it will since I have been manually fixing issues in my repo as they are created. Anyone can edit the BountySource footer in their issue details so I wouldn't expect existing issues with a bad footer to be updated; It's a part of the issue and not some embedded widget.

**Comment by Kostronor** [comment] 2017-03-30 06:47
@carlin-q-scott Since the pr is merged, I set the integration off and on and it works since then.

**Comment by snipe** [comment] 2017-03-30 06:51
@Kostronor do you mean by going to Tools and unchecking/rechecking the boxes? I've done that multiple times now with no change.

<img width="659" alt="screen shot 2017-03-29 at 11 49 10 pm" src="https://cloud.githubusercontent.com/assets/197404/24491127/9f939b40-14da-11e7-8902-cd8f38b231b3.png">

**Comment by Kostronor** [comment] 2017-03-30 06:53
I unchecked all boxes, then removed the integration, saved it. Then added it anew and checked the boxes again. It works for me at least

**Comment by antenore** [comment] 2017-03-30 06:54
@snipe , yes, but personally I've turned off the integration and only after some days after (after my PR has been merged) I've re-enabled the integration

**Comment by snipe** [comment] 2017-03-30 06:54
@Kostronor removed the integration on the GH side tho? I don't see any way to revoke from BS.

**Comment by Kostronor** [comment] 2017-03-30 06:55
@snipe I clicked the blue x on the top left side of your screenshot.

**Comment by snipe** [comment] 2017-03-30 06:56
All that does for me is minimize the panel. If I reload the tools page, it still shows two projects.

**Comment by antenore** [comment] 2017-03-30 07:02
@snipe I think it's enough to unchek "modify issue bodies". How long do you wait between the two?
I'd wait at least one day... I'm quite sure there are some scheduled tasks to modify the issue bodies

**Comment by snipe** [comment] 2017-03-30 07:06
I'm not sure - I've been trying it occasionally since the PR was merged. I've just unchecked the boxes again, and I guess I'll try re-checking them ion a few days. Weird I don't see Bountysource in my GH integrations settings for that repo tho.

**Comment by antenore** [comment] 2017-03-30 07:17
> Weird I don't see Bountysource in my GH integrations settings for that repo tho. 
I think is normal (not an official GH integration?)

**Comment by snipe** [comment] 2017-03-30 07:28
I guess - but I'd still expect to see that access granted somewhere. It *is* editing issues, so there has to be some place where that access can be revoked.

**Comment by antenore** [comment] 2017-03-30 07:37
Found. In _your_ profile settings under authorized applications

**Comment by snipe** [comment] 2017-03-30 07:40
![high-five-light](https://cloud.githubusercontent.com/assets/197404/24492731/40a55d92-14e1-11e7-9ec8-1a49cb948d53.gif)

Nice investigative work there.

I revoked that token and the repo still shows up in BS, so I guess I'll just wait a few days to re-check those boxes.

Appreciate all the suggestions!

**Comment by DarthGandalf** [comment] 2017-04-24 23:16
@rappo ping?

**Comment by PromoFaux** [comment] 2017-07-25 18:51
@snipe did it end up working for you? Facing similar issues over on pi-hole/pi-hole and pi-hole/adminLTE

**Comment by snipe** [comment] 2017-07-25 18:59
@PromoFaux Nope. Still broken. :(

**Comment by PromoFaux** [comment] 2017-07-25 19:00
*sigh* It seems to work OK when adding it to a new repo, just can't seem to fix ones that already had the integration. Be nice if they could fix this!
