### ISSUE TITLE
Cannot uninstall Bountysource from a repository

### ISSUE THREAD

**Issue by dessant** [bountysource/core#1164] opened 2017-12-20 13:43 UTC
There is an uninstall button in the source, but it is hidden and does not seem to work. How can we uninstall Bountysource from a repository?

![screenshot from 2017-12-20 15-41-24](https://user-images.githubusercontent.com/7513068/34209828-6bd956e4-e59c-11e7-8f33-84e316764a31.png)

**Comment by hjchan** [comment] 2018-03-23 04:48
duplicate of #1009

**Closed by hjchan** 2018-03-23 04:48 UTC
