### ISSUE TITLE
Github Integration no longer updating issues on installed repos

### ISSUE THREAD

**Issue by PromoFaux** [bountysource/core#1096] opened 2017-03-24 18:10 UTC
_Admin edit: $100 bounty (or more eventually) on helping get this issue fixed - see https://www.bountysource.com/issues/43409489-github-integration-no-longer-updating-issues-on-installed-repos - yes having to edit this in manually rather than rely on the GitHub integration itself may count as irony? Hard to be sure!_

Hi there,

We had this all working for some time about a year ago on https://github.com/pi-hole/pi-hole and https://github.com/pi-hole/adminLTE, but around 10 months ago (I think) it stopped working.

I've just installed the integration on a personal repo, and it appears to work there, so not really sure what has happened with the existing repos.

Is there a way to uninstall integration? 

![image](https://cloud.githubusercontent.com/assets/1998970/24307669/f0835e2c-10bc-11e7-9292-93dd643bfc45.png)

**Comment by Yehonal** [comment] 2017-03-29 15:39
my repo too is not working anymore, we've multiple bounties but no integration with git, it's very painful

**Comment by Yehonal** [comment] 2017-03-29 15:42
P.S. Why bountysource is 90% bugged lately? people is putting money not candies on issues. Please

**Comment by VanillaNinjaD** [comment] 2017-04-21 03:20
I recently had a developer recommend bountysource as a motivational tool. Shortly after that, I pledged to an open GitHub project issue and my money disappeared, I don't see it under my pledge history and it is not attached to the GitHub issue. I have sent an email to support@bountysource.com but have heard nothing back. Needless to say its frustrating at the least.

**Comment by Kostronor** [comment] 2017-05-09 11:26
@rappo any news on this issue? We got hit by it too (it worked for some months). Would posting a bunty on this help?

**Comment by snipe** [comment] 2017-07-18 00:11
We're having this issue too. Have tried disabling the integration in Tools and then re-enabling, but the bountysource footer never shows up on issues, and no integration with githib seems to be working. I'd be happy to try reinstalling it in case it would help, but I don't see a way to delete the repo to re-add. It's been broken for some time.

If there's anything I can do to help with this issue, I'd be glad to. The Bountysource integration wasn't used by everyone, but was appreciated by those that did use it. 

*waves at @VanillaNinjaD*

**Comment by PromoFaux** [comment] 2017-07-25 18:45
@rappo an official response on this would be great, thanks. The integration used to be excellent, and since it stopped working, we have missed a couple of bounties that were added to open issues. Those issues have since been closed with no resolution, which seems unfair to those that backed the bounties in the first place.

What can I do, or ask you or the team to do, in order to get this working again?

**Comment by Cervator** [comment] 2017-07-26 03:36
Alright I'm not quite as official as @rappo but until he digs out more from his day job maybe we can all try to triage this one together :-)

So the issue at hand seems to be that *existing* repositories where you went to the "Tools" menu in the past (maybe even the long past like nearly a year ago) and hooked up the integration that decorates an issue no longer works. *New* repositories that have never before been hooked up work fine if you install the integration.

A related issue is #1062 which documented a GitHub change in parsing stuff put into issues that made the integration post some now-broken markup. So it was still working, but what it was posting wasn't quite right anymore. Coincidentally (maybe) this was noted about 9 months ago.

In February, about 5.5 months ago, a fix in #1068 was submitted and merged, then deployed probably shortly after and the inserted footers started behaving again.

Not long after / around the same time some of the affected users started noting that the integration wasn't posting footers *at all* any longer to repos previously integrated. So it seems to have been broken in February/March, at least for some users. Maybe that deploy could be involved. It would be interesting if anybody could confirm having footers not getting posted in existing repos prior to that date. It sounds like it was still working in some cases, although maybe confusion over the incorrect (but working) footers is involved.

For some experimenting from me: I had lots of old repos enabled in the past and we got hit by the broken footer issue, so in trying to fix it we edited some, enabled/disabled the tool per repo, etc. I just tried a brand new never previously touched repo and the integration worked perfectly fine.

I then tried to *revoke* the Bountysource OAuth app from using my account (personal settings -> Authorized OAuth apps), confirming that the new repo no longer would get the footer posted in a new issue and I had to log out, log back in, re-authorize the app, and then I could successfully save the integration again. No dice on the old repo, still didn't get footers. No success *on the new repo either* after I had revoked and re-authorized.

So if a bunch of users after the footer started posting incorrectly attempted the revoke path (or did so for any other reasons, like simply cleaning out old tokens to then only renew what you actively used) then any old repo would likely stop working, permanently, as something doesn't clean up fully in the revoke-reauthorize flow. That would also explain some users reporting no problems (may have re-saved the integration but not revoked/reauthorized) while others could not get the footer to appear in anything but newly integrated repos.

Can anybody poke holes into that theory? Has anybody been able to post a new issue on a repo activated before a revoke, then see a footer get edited in?

If not maybe that's a spot in the code we can search for. Maybe existing integrations never try to renew *something* after a revoke, so data goes dirty and can't be reset. That sounds like a bug we can find.

Alternatively/additionally the [tools page](https://www.bountysource.com/tools) could really use the addition of a button (or two) to outright remove or reset an integration for a given repo. As noted there is no way to completely clean up the integration at present, only re-save the settings. Adding functionality to outright remove it and all related data in the DB probably would also get around this issue. Reset instead of remove could simply remove then re-add in one action. You could then also try to re-add the integration using a different account, like one you're using for bot actions rather than a personal one.

A completely different (but far more complicated) option might be looking into making a proper GitHub app for the integration instead. The Bountysource OAuth app for the integration is 5 years old at this point.

Maybe one of the recent volunteers interested in becoming a core dev could try this bug out. Will Drop a link to it on Slack/IRC as well, maybe channel ping in a few days if it doesn't have any takers yet.

**Comment by snipe** [comment] 2017-07-26 03:56
> I then tried to revoke the Bountysource OAuth app from using my account (personal settings -> Authorized OAuth apps), confirming that the new repo no longer would get the footer posted in a new issue and I had to log out, log back in, re-authorize the app, and then I could successfully save the integration again. No dice on the old repo, still didn't get footers. No success on the new repo either after I had revoked and re-authorized.

I can confirm this behavior on our (older) repo. Our footer/badge integration stopped working some time ago. I tried unchecking the boxes in the tools section to "diable" the integration via BS. I then waited a few days (in case there was any synchronization that had to happen on the BS side), and re-checked those boxes. Waited another few days, with no change.

I tried revoking via GH, logging out out BS, logging back in, re-adding it, no dice. (I have my attempts documented in another issue, but I can't find it at the moment, and just wanted to confirm that this is what I'm seeing as well. 

I can tell you that I'm the only person who futzes with the repo in Bountysource, so there isn't a possibility of conflicting BS/GH Repo Owner actions. 

I do wish I could remember when they stopped working for us, but I'm honestly not sure. I'm sorry.

**Comment by PromoFaux** [comment] 2017-07-26 11:55
>It would be interesting if anybody could confirm having footers not getting posted in existing repos prior to that date.

So according to a quick search of our [open and closed issues](https://github.com/pi-hole/pi-hole/issues?q=Want+to+back+this+issue%3F+Post+a+bounty+on+it%21+We+accept+bounties+via+Bountysource.+sort%3Acreated-desc), the last time the integration worked (for us, atleast) was october 2016

**Comment by Cervator** [comment] 2017-08-11 20:23
Just added a $100 bounty on this, not that you'd be able to rely on the GitHub plugin to let you know since ... yeah this issue is about getting that fixed :D

While reworking the OAuth app / plugin into an outright [GitHub Integration](https://github.com/blog/2226-build-an-integration-for-github) would be nicer, that's probably a fair bit more work. Chances are something just changed with the GitHub OAuth stuff over the years and the token revocation thing wasn't considered (or done right) when the integration was originally written.

**Comment by Cervator** [comment] 2017-08-16 23:23
Nice catch @Denu8thell ! Where did you find that? I didn't even realize there was a lock system like that. Not that I've dug very deep so far.

Your first suggestion sounds fine, main concern I'd have is whether it would be a hassle to develop and/or if it would be a hassle for users to discover the problem and solve it on their own after the updates are made.

With GitHub integrations released I imagine the long term fix would be a new non-user based application to replace the old plugin. So I wouldn't want anybody to sink too much effort into the old plugin. Although we do need it to work again ASAP :-)

My thought on uninstalling the plugin was in case that helps reset whatever gets stuck. If an enhancement to interact with locks fixes the issue entirely then yeah outright uninstall becomes lower priority.

**Comment by Denu8thell** [comment] 2017-08-17 00:06
Alright, I'm gonna work on the first proposed solution then. I really don't think it should be so difficult to implement, and even if it is, I got some time to spend on it. 

I don't really know what to do about helping users figure out that this is even a problem, particularly after the updating. I'll think about it.

**Comment by Cervator** [comment] 2017-08-17 01:10
At least we can update the documentation and point users to it when the issue occurs. Lots of users probably use it without ever revoking in the first place.

Thanks! :-)

Let me know if you'd like a Slack invite somewhere, just need to get an email address to me or @rappo (maybe PM on IRC)

**Comment by Denu8thell** [comment] 2017-08-19 16:22
@Cervator I have a pull request with an initial fix to this problem, if you or anybody else could find time to review it, that'd be great. I'll try to get an email to you on IRC in a bit.

**Comment by Cervator** [comment] 2017-08-19 16:45
Yep thanks I saw it - trying to poke @rappo to check it out :-)

**Comment by PromoFaux** [comment] 2017-12-07 23:05
Ping! Any update?

**Comment by Cervator** [comment] 2017-12-07 23:34
Pong :-)

So the GitHub API issue has been resolved so that was a pretty important step to get out of the way.

Now that shouldn't be an issue in testing out and merging this. Just need @wkonkel or @rappo to take a look, merge, and deploy

**Comment by VanillaNinjaD** [comment] 2017-12-07 23:35
It looks like there have been 3 or 4 more issues relating to the Github integration. I spied one pull request related to fixing the issue but not much other movement. Granted I just checked in today when I got the ping

https://github.com/bountysource/core/pull/1130

**Comment by VanillaNinjaD** [comment] 2017-12-07 23:35
@cervator you are fast!!!

**Comment by snipe** [comment] 2017-12-08 00:02
Awesome, thanks! Any idea when that PR will be able to reviewed/merged?

**Comment by Cervator** [comment] 2017-12-08 03:10
Right now most of what little admin effort is available is being consumed by end-of-year stuff - taxes, finance docs, that sort of thing. But I'm trying to highlight the PR associated with this as top of the list if some spare time pops up. A little merging here and there goes a long way!

**Comment by JalenOng** [comment] 2018-03-02 21:59
Hey @snipe, @VanillaNinjaD @PromoFaux @Yehonal, @Cervator we are the new team looking into the issue. Since we don't have any test data to work with, can you guys share some repo/tracker links that are not updating? If you can share your first name too, that would be great. Appreciate your privacy, so share whatever that you feel comfortable with. Can also email me at jalen.ong@gmail.com. Thanks!

**Comment by snipe** [comment] 2018-03-02 22:09
Hi @JalenOng - no problem. My first name is Alison.

- https://github.com/snipe/snipe-it - repo
- https://www.bountysource.com/teams/snipe-it - BS link
- https://www.bountysource.com/issues/26718575-feature-request-insurance-for-equipment - example bounty'd issue
- https://github.com/snipe/snipe-it/issues/1176 - example original issue with no BS integration

**Comment by Yehonal** [comment] 2018-03-02 23:02
Hi @JalenOng , Yehonal Here and nice to meet you! I hope bountysource can
be boosted with this new team :)


https://github.com/azerothcore/azerothcore-wotlk (repo)
https://www.bountysource.com/teams/azerothcore/issues (bountysource)

Currently i'm manually adding the badge to the issues because it doesn't
happen automatically



2018-03-02 23:09 GMT+01:00 snipe <notifications@github.com>:

**Comment by VanillaNinjaD** [comment] 2018-03-02 23:32
Thanks @JalenOng!

My first name is Cole. I’ll be the first to admit that while i’m an IT professional and a full-time tinkerer I am not a developer.

I’ll keep my eyes peeled for absolutely any way that I can help though!

**Comment by JalenOng** [comment] 2018-03-03 20:30
@snipe @Yehonal, really appreciate the data. Thank you. Will update soon!

@VanillaNinjaD Thank you! Aren't they all just labels :)

**Comment by CendioOssman** [comment] 2018-03-05 10:07
Glad to see this progressing and #1130 merged. :)

Does this mean that the issue is fixed and we'll be getting proper updates?

And what happens to all existing entries in our repos? Will they be adjusted automatically, or do we need to do something?

**Comment by NoNonsense126** [comment] 2018-03-05 10:42
You'll need to unlock repos that aren't updating.

Go to https://www.bountysource.com/tools

You'll find that the project that's not updating to be locked (Let me and @JalenOng know if it isn't!). Just uncheck 'This project is locked' and click save. If all is well, all the issues within that repo should be updated within a few minutes. 

Let us know if it works for you :)

**Closed by NoNonsense126** 2018-03-05 10:42 UTC
Labels: GitHub plugin, bounty

**Comment by CendioOssman** [comment] 2018-03-05 10:53
Great, thanks. That worked perfectly. :)

**Comment by PromoFaux** [comment] 2018-03-05 12:23
@NoNonsense126, One of our repos just goes back to locked again after I uncheck it and then click save... any thoughts?

**Comment by NoNonsense126** [comment] 2018-03-05 12:40
What's the repo name?

**Comment by PromoFaux** [comment] 2018-03-05 12:41
pi-hole/pi-hole

**Comment by NoNonsense126** [comment] 2018-03-05 13:20
@PromoFaux It should be fixed now.

**Comment by PromoFaux** [comment] 2018-03-05 13:23
Yeah, just saw all the webhooks coming through for that repo.. thanks!
![image](https://user-images.githubusercontent.com/1998970/36977165-23438b36-2078-11e8-8efa-96273773ba8d.png)

**Comment by Flaburgan** [comment] 2018-03-05 14:50
@NoNonsense126 https://www.bountysource.com/tools doesn't list `diaspora/diaspora` even if I'm admin of that team on bounty source and a member of the [organization](https://github.com/orgs/diaspora/people)

**Comment by NoNonsense126** [comment] 2018-03-05 14:53
You need to be a public member of the organization

**Comment by snipe** [comment] 2018-03-06 03:03
@JalenOng @NoNonsense126 it worked - thanks so much!!

**Comment by Flaburgan** [comment] 2018-03-06 10:09
@NoNonsense126 what's the difference with the link I posted? (As you can see I appear in people).

**Comment by NoNonsense126** [comment] 2018-03-06 10:13
@Flaburgan No, I don't see you in the link you shared. 

Perhaps you can try it in incognito mode/ when you're not logged in?

**Comment by Flaburgan** [comment] 2018-03-06 10:25
Alright I just set my visibility from private to public sorry. It still doesn't appear at the moment but I guess I should wait a bit. However this makes me wondering how the rights check is done in bounty source, because I already granted access to my account so you should be able to check that I have write access to the repository using the github API. Are you manually parsing the people page of the organization? I guess not but eh :p

**Comment by Cervator** [comment] 2018-03-06 21:28
Awesome to see this get merged :-)

For a general note / reminder: this current integration is very old and predates the introduction of the new more *full* GitHub applications. I'd love to just see this one stabilized then eventually introduce a full replacement that has all the bells and whistles

**Comment by PromoFaux** [comment] 2018-04-10 10:02
@NoNonsense126 ... How can I completely remove the integration from a repo? The only option I can see on the site is to just untick it's permissions.
