### ISSUE TITLE
GitHub Commiter Tools doesn't work

### ISSUE THREAD

**Issue by Diaoul** [bountysource/core#1142] opened 2017-10-04 19:36 UTC
I think it's been a year now that the GitHub Commiter Tools doesn't work for https://github.com/SynoCommunity/spksrc/
In addition to wait for the bug to resolve itself over a long period of time, I've tried to tick/untick the checkboxes for integration without luck.

Here is an example of an issue that received a bounty recently but I updated the tags and title manually : https://github.com/SynoCommunity/spksrc/issues/2939

**Comment by Denu8thell** [comment] 2017-10-04 19:58
Duplicate of #1096?

**Comment by rappo** [comment] 2017-12-10 01:29
yes, dupe of #1096

**Closed by rappo** 2017-12-10 01:29 UTC
