### ISSUE TITLE
Please make it privacy friendly - salt does not load with reasonable privacy

### ISSUE THREAD

**Issue by stacksmith** [bountysource/core#1052] opened 2016-10-09 19:49 UTC
Salt locks up the browser and behaves erratically on my browser.  I was unable to contribute to a project for several days.  

My browser has a minimal privacy setup:
https everywhere
uMatrix
self-destructing cookies

Even turning these off I am unable to load the site.  You can't expect someone to install a browser with no privacy protection just to use your site.

Please have some respect for your users and remove google, google analytics, and anything else that is not necessary for the site operation.  At least make it work if the browser blocks google tracking.

**Comment by rappo** [comment] 2016-10-24 11:10
@stacksmith thanks for reporting, but I think your setup is unrelated. We're having a number of issues around AWS that we need to address, but haven't yet had the time. You should definitely be able to browse with those extensions, assuming you're not also anti-JS. Closing because the issue isn't privacy related, but AWS/hosting related.

**Closed by rappo** 2016-10-24 11:10 UTC

**Comment by stacksmith** [comment] 2016-10-24 15:38
Thank you, that is fair enough.
