### ISSUE TITLE
Issue tracker not showing up?

### ISSUE THREAD

**Issue by lily-seabreeze** [bountysource/core#986] opened 2015-11-15 05:45 UTC
I can see the issue tracker here: https://www.bountysource.com/trackers/7646105-hypatia-engine-hypatia

But I cannot add this project's issue tracker to my team.
##

**Comment by svnpenn** [comment] 2015-11-28 19:37
:+1:

**Comment by svnpenn** [comment] 2015-11-28 19:59
https://github.com/bountysource/core/issues/948

**Comment by svnpenn** [comment] 2015-11-28 19:59
https://github.com/bountysource/core/issues/962

**Comment by rappo** [comment] 2017-03-06 00:18
closing, dupe of https://github.com/bountysource/core/issues/948

**Closed by rappo** 2017-03-06 00:18 UTC
