### ISSUE TITLE
Bountysource makes inconsistent statements about fees

### ISSUE THREAD

**Issue by sampablokuper** [bountysource/core#1042] opened 2016-07-27 21:35 UTC
[core/app/assets/javascripts/app/about/terms.html](https://github.com/bountysource/core/blob/master/app/assets/javascripts/app/about/terms.html) says:

> 2.1 A Backer pays Bountysource to encourage the development of a successful Solution to an Issue.  Bountysource will then post the terms of the Bounty on the Bountysource.com website. Backers must provide their payment at the time they create a Bounty. Backers consent to Bountysource and its payments partners charging their payment card or other payment method for the amount of their payment. Bounties are nonrefundable and an additional 10% charge is added at the time of payment (a Backer will be charged $110 for $100 Bounty).

This directly contradicts [core/app/assets/javascripts/app/about/fees.html], which says:

>  <p>There are no fees associated with posting a bounty, pledging a fundraiser, or gifting to a team. All payment processing fees are covered by Bountysource.</p>
>   <p>For example, posting a $1000 bounty from Paypal costs you exactly $1000.</p>

and the FAQ, [which says](https://github.com/bountysource/core/wiki/Frequently-Asked-Questions#what-does-it-cost-to-post-a-bounty):

> There are no fees associated with posting a bounty. For example, to post a $500 bounty, you will be charged $500.
- Which of these statements is/are correct?
- Please can this matter be made [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself) (i.e. to use a [single source of truth](https://en.wikipedia.org/wiki/Single_Source_of_Truth)), by:
  1. retaining only _one_ of the above mentions of fees,
  2. making sure it is correct, and
  3. replacing the other mentions of fees with links to that single source of truth (e.g. "See [Fees](https://bountysource.com/fees).")?

**Comment by brianhks** [comment] 2016-08-03 19:49
Duplicate of #994

**Closed** 2018-03-14 05:12 UTC
