### ISSUE TITLE
Fee in fees page and TOS do not match.

### ISSUE THREAD

**Issue by dekarl** [bountysource/core#994] opened 2015-12-23 12:20 UTC
The [fees page](https://www.bountysource.com/fees) says:
All payment processing fees are covered by Bountysource.
For example, posting a $1,000 bounty from Paypal costs you exactly $1,000.

The [terms of service](https://www.bountysource.com/terms) say:
2.1 ... Backers consent to Bountysource and its payments partners charging their payment card or other payment method for the amount of their payment. Bounties are nonrefundable and an additional 10% charge is added at the time of payment (a Backer will be charged $110 for $100 Bounty).

It appears as if one is right and the other is wrong. I suggest to change the one that does not reflect reality.

**Comment by sampablokuper** [comment] 2016-08-09 23:18
> It appears as if one is right and the other is wrong.

The FAQ is another location with a potentially incorrect claim. See #1042 (which was closed - with only partial justification - as a duplicate of this issue) for the details.

> I suggest to change the one that does not reflect reality.

Please can this matter be made [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself) (i.e. to use a [single source of truth](https://en.wikipedia.org/wiki/Single_Source_of_Truth)), by:

    1. retaining only *one* piece of documentation about fees,
    1. making sure that piece of documentation is correct, and
    1. replacing the other mentions of fees with links to that single source of truth (e.g. "See [Fees](https://bountysource.com/fees).")?

**Comment by sampablokuper** [comment] 2016-08-10 00:06
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=29358480)](https://www.bountysource.com/issues/29358480-fee-in-fees-page-and-tos-do-not-match?utm_source=29358480&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by bjorn** [comment] 2017-09-26 19:47
The terms of service are out of date in this case. The fee used to be charged on payment, but since some years they are charged on cash out.

**Comment by nicolas17** [comment] 2017-09-27 01:17
You have to formally agree to a legal document that is known to be wrong for at least 2 years, how fun.

**Closed** 2018-03-14 05:12 UTC

**Comment by sampablokuper** [comment] 2018-03-14 05:41
@hjchan, what was the basis for closing this? Has the issue been fixed? If so, in which commit?

It would be great if you could post that info instead of just closing the issue without explanation. Thanks.

**Comment by hjchan** [comment] 2018-03-14 06:05
The issue was fixed in commit d08888d83d6d98255e1a1908aa320692911003ea

**Comment by bjorn** [comment] 2018-03-14 09:35
Seems like it's about time @rappo claimed the $5 bounty. :-)

**Comment by mojo706** [comment] 2018-06-30 13:13
if the issue has been fixed then I guess you should remove it from the README. 
![screen shot 2018-06-30 at 16 12 11](https://user-images.githubusercontent.com/908380/42125483-7a589c04-7c80-11e8-8509-2746b260129a.png)

I can remove it.
