### ISSUE TITLE
Bountysource search doesn't find any of my projects by name, only by URL [$5]

### ISSUE THREAD

**Issue by dessalines** [bountysource/core#957] opened 2015-04-14 20:46 UTC
I have bountysource installed for several projects, but you can only find them by typing in the URL, not the project name.

For example, searching for:
`https://github.com/tchoulihan/bitmerchant` works
`bitmerchant` doesn't.
##

**Comment by tchoulihan** [comment] 2015-04-19 02:14
Is bountysource dead? It appears they've added no new projects to their front-end tracker for more than 6 months.

**Comment by tchoulihan** [comment] 2015-04-19 02:14
Is bountysource dead? It appears they've added no new projects to their front-end tracker for more than 6 months.

**Comment by kazssym** [comment] 2015-04-19 09:00
Apparently, they have removed all the frontend code from GitHub (at least from the master branch).  Anybody else can no longer fix problems in Bountysource.

**Comment by rappo** [comment] 2015-04-19 21:59
@tchoulihan GitHub issues and repos are updated instantly and all existing GitHub repo should be found on Bountysource. For instance, the repo you linked can be found at https://www.bountysource.com/trackers/9805417-tchoulihan-bitmerchant.

It appears as if there's a problem with our search results / indexing, I'll look into that and report back.

**Comment by tchoulihan** [comment] 2015-04-19 22:04
> It appears as if there's a problem with our search results / indexing

That's what I'm referring to. I can't search for my projects, and also, I can't add any *non-searchable* projects to my team's watched projects.

**Comment by kazssym** [comment] 2015-04-19 22:43
Issue #939 seems a duplicate of this one.

**Comment by kazssym** [comment] 2015-05-13 01:56
Any progress on this issue?

**Comment by frnco** [comment] 2017-06-01 06:49
@rappo this also seems to be working again, should be closed.

**Closed** 2017-06-02 03:05 UTC
Labels: bounty
