### ISSUE TITLE
"Add an issue tracker that your team manages" does not do anything

### ISSUE THREAD

**Issue by kathyqian** [bountysource/core#1023] opened 2016-05-13 14:18 UTC
This may just be a UX issue, but I cannot add any issue trackers to my team. I have tried pasting the URL of the issue tracker into the "Add an issue tracker that your team manages" search box, but it doesn't seem to do anything. 

I tried pasting the issue tracker URL into the main search box, and it just created a new team (ugh). I'm confused. How do I add the existing issue trackers from my Github organization into my Bountysource team?

**Comment by rappo** [comment] 2016-05-19 23:06
confirmed, this is a known issue.

To work around this, please join #Bountysource on irc.freenode.com and ask me for support, or email support@bountysource.com.

**Comment by svnpenn** [comment] 2016-05-19 23:23
Same problem. I put in a request for this on April 6, and just got a response today? And not a response that the issue was fixed, but that it is a known issue? Is anyone even working on this project? This seems to be a critical issue that is being ignored. I am considering switching to Gratipay

**Comment by svnpenn** [comment] 2016-05-19 23:25
Same problem. I put in a request for this on April 6, and just got a response
today? And not a response that the issue was fixed, but that it is a known
issue? Is anyone even working on this project? This seems to be a critical issue
that is being ignored. I am considering switching to Gratipay.

The devs are fixing syntax errors and ignoring important issues?

http://github.com/bountysource/core/commit/f571dcc

**Comment by rappo** [comment] 2016-05-20 00:04
@svnpenn We're working on this on a volunteer basis and there's a MASSIVE difference between a 1 minute typo fix and looking into a issue like this (which is also very low priority). Please make sure your comments and feedback are constructive.

I can vouch for the Gratipay team, they're a good group of people. If you'd prefer their service (even though they don't even support bounties or issue trackers, making it a moot argument on this specific topic), by all means support them.

**Comment by svnpenn** [comment] 2016-05-20 00:28
@rappo heres something constructive:

I originally emailed about this issue November 2015. Thats 6 months ago. This
issue is not "low priority", how could it be?

The first thing you do after creating a team is add issue trackers. How could
an app breaking feature be considered low priority? Low priority is changing
an uppercase B to a lowercase b. The fact that I have to explain this is pretty
sad.

Dont tell me about volunteer, I know about open source:

http://github.com/svnpenn

You want people to put MONEY into your site via bounties, you might start taking
it seriously.

**Comment by kathyqian** [comment] 2016-05-20 01:38
It's great to know that this is a known issue. As someone using BountySource for the first time, it would have been helpful to know that the issue was known and there was a workaround off the bat - perhaps even a simple "To work around this, please join #Bountysource on irc.freenode.com and ask me for support, or email support@bountysource.com." like above on the page could do the trick!

**Comment by nijel** [comment] 2016-10-20 11:06
Any progress on this? It makes it really impossible to include newly created repos under the organization. As support@bountysource.com seems to be close to /dev/null (I got no response on previous requests), I'm afraid that's not going to help either...

**Comment by svnpenn** [comment] 2016-10-20 11:30
https://github.com/bountysource/core/issues/1046

**Comment by svnpenn** [comment] 2016-10-20 11:30
https://github.com/bountysource/core/issues/1020

**Comment by rappo** [comment] 2016-10-24 11:05
@nijel There are no open support@bountysource.com issues pending from you. Can you please double check the request that you sent? Thanks!

And to answer your question -- there is no update. We hope to be back supporting Bountysource with bug fixes and new features in January. For now, we're struggling to find time for all of the requests and we're in "keep alive" mode. Hopefully this changes in a few months.

That said, newly created repos should automatically be added to any team that is already associated with a GitHub Org. If that's not the case, that's a new bug that hasn't been reported yet.

**Comment by jcrben** [comment] 2017-02-14 03:32
@rappo could you add a confirmed label for confirmed bugs? it can make a difference for those who want to help fix things.

**Comment by rappo** [comment] 2017-07-15 23:19
@jcrben (extremely late reply) - That's how I've been using the two bug tags (bug - visual, bug - functional). I've applied that to this issue/

**Comment by svnpenn** [comment] 2017-07-16 12:34
@rappo pretty sad that this critical issue is still open over a year later

**Comment by jcrben** [comment] 2017-07-16 18:09
@rappo to clarify, how are you tagging bugs without a solid reproduction? or are you just closing them?

**Comment by PeterDaveHello** [comment] 2020-02-01 18:56
@sivaraam  Looks like the issue still exists, the function is still not working.

**Closed** 2020-03-10 05:29 UTC
Labels: bug - functional, ⚠Critical⚠
