### ISSUE TITLE
Project settings doesn't work: can't add projects

### ISSUE THREAD

**Issue by Yehonal** [bountysource/core#1097] opened 2017-03-29 15:42 UTC
![image](https://cloud.githubusercontent.com/assets/147092/24463318/bf6c93f6-14a6-11e7-9786-cfac677cd2f0.png)

I can't add project again after removed, the search box doesn't work

**Comment by rappo** [comment] 2017-04-06 07:13
dupe of https://github.com/bountysource/core/issues/1023

**Closed by rappo** 2017-04-06 07:13 UTC
