### ISSUE TITLE
Canceling Bounties

### ISSUE THREAD

**Issue by nathanathan** [bountysource/core#945] opened 2015-02-01 11:24 UTC
I have a few bounties from almost a year ago that I am beginning to suspect nobody will claim. So the money doesn't go to waste, I think there should be an option to cancel bounties after a few months with the stipulation that nobody has clicked on the "I'm working on this" button.
##

**Comment by x-a-n-a-x** [comment] 2015-02-02 19:12
I agree too. 

I have created bounties on a few issues but after many months without activity, it seems that developers are or focusing on other tasks or don't want (nor plan) to work on the issues I like.

I wish there could be a way to get the money back after 1 year.

**Comment by rappo** [comment] 2015-02-19 00:46
+1

The ability to refund to your Bountysource account as long as no one is working on the issue is definitely needed and planned.

**Comment by frndxyz** [comment] 2015-04-06 12:39
bountysource doing it like legal scam.

**Comment by rappo** [comment] 2015-04-07 02:49
I'm sorry @frndxyz but I don't see how your comment is useful or appropriate. Bountysource does refund any bounties that no one is working on when asked. We simply don't yet have a mechanism to do it through the app. I'm sure both @nathanathan and @x-a-n-a-x can back us up here, as I'm fairly certain they've both had bounties refunded.

**Comment by x-a-n-a-x** [comment] 2015-04-07 05:01
I confirm what rappo said. 
I joined the Bountysource IRC channel, I explained them what my problem was, and they kindly refunded me.

**Comment by frndxyz** [comment] 2015-04-09 06:39
@rappo  can you please cancel my bounty https://www.bountysource.com/issues/10551169-lyra2re-neoscrypt-quark-algo-support-in-c-placing-bounty-30/backers . i solved the issue  myself.

**Comment by rappo** [comment] 2015-04-09 06:47
@frndxyz sure thing! if you're the backer, just email support@bountysource.com from the email you have on file with Bountysource and we'll take care of it ASAP.

**Comment by frndxyz** [comment] 2015-04-09 07:15
@rappo  thanks i send it.

**Comment by dogancelik** [comment] 2016-04-08 23:36
:+1:
There is a project that is almost dead and totally not responded by the developer or anybody else (almost been a year). I would like to take my dead-end bounties and donate them to important projects that actually needs the money (using normal way through bounties or using Salt).

**Comment by rappo** [comment] 2017-03-05 22:50
added details and a $100 bounty (now $150) to https://github.com/bountysource/core/issues/1028#issuecomment-284270012, closing this duplicate.

**Closed by rappo** 2017-03-05 22:50 UTC

**Comment by ashtonhogan** [comment] 2018-01-29 10:01
@rappo I have contacted you guys a few weeks ago regarding a refund on dead bounties but haven't received any response?

**Comment by Cervator** [comment] 2018-01-29 15:21
Hey @ashtonhogan - combination of holidays + acquisition + me personally being out of the country for a month plus change so not checking support. Getting back into it now and I found your request and replied. Lets continue there :-)
